// BACKEND/src/constants/roles.js
// Maps each role to its set of base permissions.
// These are the default permissions granted by role membership alone.
// Per-user overrides (customPermissions.granted / .revoked) are applied on top.

import { PERMISSIONS } from './permissions.js';

const P = PERMISSIONS;

// ─── Shared Permission Groups ────────────────────────────────────────────────

const COMMON_READ = [
  P.BRANDING_READ,
  P.NOTIFICATIONS_READ,
  P.SETTINGS_READ,
  P.ACADEMIC_YEARS_READ,
  P.COUNTRIES_READ,
  P.STATES_READ,
  P.COUNTIES_READ,
  P.SEARCH_GLOBAL,
];

const TEACHER_PERMISSIONS = [
  ...COMMON_READ,
  P.SUBJECTS_READ,
  P.CLASSES_READ,
  P.STUDENTS_READ,
  P.DEPARTMENTS_READ,
  P.ATTENDANCE_READ,
  P.ATTENDANCE_MARK,
  P.ATTENDANCE_UPDATE,
  P.ANNOUNCEMENTS_READ,
  P.ANNOUNCEMENTS_CREATE,
  P.ANNOUNCEMENTS_UPDATE,
  P.ANNOUNCEMENTS_PIN,
  P.ASSIGNMENTS_READ,
  P.ASSIGNMENTS_CREATE,
  P.ASSIGNMENTS_UPDATE,
  P.ASSIGNMENTS_GRADE,
  P.GRADES_READ,
  P.GRADES_CREATE,
  P.GRADES_UPDATE,
  P.EXAMS_READ,
  P.EXAMS_CREATE,
  P.EXAMS_UPDATE,
  P.TIMETABLE_READ,
  P.REPORTS_READ,
  P.REPORT_CARDS_READ,
  P.LIBRARY_READ,
  P.SETTINGS_UPDATE,
  P.DISCIPLINE_READ,
];

const SCHOOL_ADMIN_PERMISSIONS = [
  ...TEACHER_PERMISSIONS,
  P.TEACHERS_READ,
  P.TEACHERS_CREATE,
  P.TEACHERS_UPDATE,
  P.STUDENTS_CREATE,
  P.STUDENTS_UPDATE,
  P.PRINCIPALS_READ,
  P.CLASSES_CREATE,
  P.CLASSES_UPDATE,
  P.SUBJECTS_CREATE,
  P.SUBJECTS_UPDATE,
  P.ANNOUNCEMENTS_DELETE,
  P.ASSIGNMENTS_DELETE,
  P.GRADES_DELETE,
  P.EXAMS_DELETE,
  P.ATTENDANCE_DELETE,
  P.ENROLLMENT_READ,
  P.ENROLLMENT_CREATE,
  P.ENROLLMENT_APPROVE,
  P.TIMETABLE_CREATE,
  P.TIMETABLE_UPDATE,
  P.DEPARTMENTS_CREATE,
  P.DEPARTMENTS_UPDATE,
  P.REPORT_CARDS_CREATE,
  P.BRANDING_UPDATE,
  P.LIBRARY_MANAGE,
  P.DISCIPLINE_CREATE,
  P.DISCIPLINE_UPDATE,
  P.NOTIFICATIONS_SEND,
  P.USERS_READ,
  P.SCHOOLS_READ,
];

const DISTRICT_ADMIN_PERMISSIONS = [
  ...SCHOOL_ADMIN_PERMISSIONS,
  P.SCHOOLS_READ,
  P.SCHOOLS_CREATE,
  P.SCHOOLS_UPDATE,
  P.TEACHERS_DELETE,
  P.STUDENTS_DELETE,
  P.PRINCIPALS_CREATE,
  P.PRINCIPALS_UPDATE,
  P.CLASSES_DELETE,
  P.SUBJECTS_DELETE,
  P.ENROLLMENT_DELETE,
  P.TIMETABLE_DELETE,
  P.DEPARTMENTS_DELETE,
  P.DISTRICTS_READ,
  P.DISTRICTS_UPDATE,
  P.SUBSCRIPTIONS_READ,
  P.USERS_CREATE,
  P.USERS_UPDATE,
  P.ROLES_READ,
  P.ACADEMIC_YEARS_MANAGE,
];

const SUPER_ADMIN_PERMISSIONS = Object.values(P);

// ─── Role-Permission Map ─────────────────────────────────────────────────────

export const ROLE_PERMISSIONS = {
  super_admin:        SUPER_ADMIN_PERMISSIONS,
  district_admin:     DISTRICT_ADMIN_PERMISSIONS,
  district_superintendent: DISTRICT_ADMIN_PERMISSIONS,
  school_admin:       SCHOOL_ADMIN_PERMISSIONS,
  vice_principal:     [
    ...SCHOOL_ADMIN_PERMISSIONS.filter((p) => !p.endsWith(':delete')),
  ],
  office_admin: [
    ...COMMON_READ,
    P.STUDENTS_READ,
    P.TEACHERS_READ,
    P.CLASSES_READ,
    P.ENROLLMENT_READ,
    P.ENROLLMENT_CREATE,
    P.ANNOUNCEMENTS_READ,
    P.SCHOOLS_READ,
    P.DEPARTMENTS_READ,
    P.USERS_READ,
    P.SETTINGS_UPDATE,
  ],
  department_head: [
    ...TEACHER_PERMISSIONS,
    P.TEACHERS_READ,
    P.DEPARTMENTS_UPDATE,
    P.SUBJECTS_CREATE,
    P.SUBJECTS_UPDATE,
    P.CLASSES_CREATE,
    P.CLASSES_UPDATE,
  ],
  teacher:             TEACHER_PERMISSIONS,
  teaching_assistant:  TEACHER_PERMISSIONS,
  counselor: [
    ...COMMON_READ,
    P.STUDENTS_READ,
    P.DISCIPLINE_READ,
    P.DISCIPLINE_CREATE,
    P.DISCIPLINE_UPDATE,
    P.REPORTS_READ,
    P.ATTENDANCE_READ,
    P.ANNOUNCEMENTS_READ,
    P.NOTIFICATIONS_SEND,
  ],
  librarian: [
    ...COMMON_READ,
    P.LIBRARY_READ,
    P.LIBRARY_MANAGE,
    P.STUDENTS_READ,
    P.TEACHERS_READ,
    P.ANNOUNCEMENTS_READ,
  ],
  nurse: [
    ...COMMON_READ,
    P.STUDENTS_READ,
    P.ATTENDANCE_READ,
    P.REPORTS_READ,
  ],
  coach: [
    ...TEACHER_PERMISSIONS,
    P.DISCIPLINE_CREATE,
    P.DISCIPLINE_UPDATE,
  ],
  student: [
    P.BRANDING_READ,
    P.NOTIFICATIONS_READ,
    P.SUBJECTS_READ,
    P.CLASSES_READ,
    P.ASSIGNMENTS_READ,
    P.GRADES_READ,
    P.ATTENDANCE_READ,
    P.ANNOUNCEMENTS_READ,
    P.EXAMS_READ,
    P.TIMETABLE_READ,
    P.LIBRARY_READ,
    P.REPORT_CARDS_READ,
    P.SETTINGS_READ,
    P.SETTINGS_UPDATE,
    P.SEARCH_GLOBAL,
  ],
  parent: [
    P.BRANDING_READ,
    P.NOTIFICATIONS_READ,
    P.STUDENTS_READ,
    P.GRADES_READ,
    P.ATTENDANCE_READ,
    P.ANNOUNCEMENTS_READ,
    P.ASSIGNMENTS_READ,
    P.REPORT_CARDS_READ,
    P.SEARCH_GLOBAL,
  ],
  board_member: [
    ...COMMON_READ,
    P.SCHOOLS_READ,
    P.DISTRICTS_READ,
    P.REPORTS_READ,
    P.STUDENTS_READ,
    P.TEACHERS_READ,
    P.SUBSCRIPTIONS_READ,
    P.AUDIT_READ,
  ],
  hr_manager: [
    ...COMMON_READ,
    P.TEACHERS_READ,
    P.TEACHERS_CREATE,
    P.TEACHERS_UPDATE,
    P.PRINCIPALS_READ,
    P.PRINCIPALS_CREATE,
    P.PRINCIPALS_UPDATE,
    P.USERS_READ,
    P.USERS_CREATE,
    P.USERS_UPDATE,
    P.DEPARTMENTS_READ,
    P.SCHOOLS_READ,
  ],
  hr_staff: [
    ...COMMON_READ,
    P.TEACHERS_READ,
    P.PRINCIPALS_READ,
    P.USERS_READ,
    P.DEPARTMENTS_READ,
    P.SCHOOLS_READ,
  ],
  finance_manager: [
    ...COMMON_READ,
    P.SUBSCRIPTIONS_READ,
    P.SUBSCRIPTIONS_MANAGE,
    P.REPORTS_READ,
    P.SCHOOLS_READ,
    P.DISTRICTS_READ,
    P.USERS_READ,
    P.AUDIT_READ,
  ],
  finance_clerk: [
    ...COMMON_READ,
    P.SUBSCRIPTIONS_READ,
    P.REPORTS_READ,
    P.SCHOOLS_READ,
  ],
  payroll_specialist: [
    ...COMMON_READ,
    P.TEACHERS_READ,
    P.USERS_READ,
    P.REPORTS_READ,
    P.SCHOOLS_READ,
  ],
};

/**
 * Get all permissions for a given role.
 * Deduplicates in case a role inherits the same permission multiple times.
 */
export const getPermissionsForRole = (role) => {
  return [...new Set(ROLE_PERMISSIONS[role] || [])];
};

export default ROLE_PERMISSIONS;
